GET http://localhost:5000/api

######## 教師 #######
###
GET http://localhost:5000/api/teacher

###
GET http://localhost:5000/api/teacher/Run

###

POST http://localhost:5000/api/teacher
Content-Type: application/json

{
  "name": "Run",
  "salary": 800,
  "subjects": "木吉他"
}

###
PATCH http://localhost:5000/api/teacher
Content-Type: application/json

{
  "name": "Run",
  "salary": 1200,
  "subjects": "木吉他 ｜ 電吉他"
}

###
DELETE http://localhost:5000/api/teacher/Kai

###
DELETE http://localhost:5000/api/teacher/



######## 學生 #######
###
GET http://localhost:5000/api/student

###
GET http://localhost:5000/api/student/aa

###
POST http://localhost:5000/api/student/
Content-Type: application/json

{
  "name": "studentC",
  "teacher_name": "Run"
}

###
DELETE http://localhost:5000/api/student/studentC

###
DELETE http://localhost:5000/api/student/

